; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:t5-epaper-s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200

build_src_filter =
	-<*>
    +<main_epaper.cpp>
    +<display.cpp>
    +<epaper_sender_ble.cpp>
    +<location.cpp>
    +<wifi_scanner.cpp>

; Speicher freischalten (16MB Flash / 8MB PSRAM für das E-Paper)
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv


build_flags =
    -D BOARD_HAS_PSRAM
    -D ARDUINO_USB_CDC_ON_BOOT=1    ; Startet Ausgabe von Texten sofort (damit beim Booten alles tdm alles im Terminal ladnet)

lib_deps =
    https://github.com/Xinyuan-LilyGO/LilyGo-EPD47#esp32s3

upload_port = COM3 ; Change -> PIO Home -> left hand Devices -> Port
monitor_port = COM3 ; Durch die Angabe von Port könnte man mehrere Geräte angesteckt haben und mit wechsel der ENV wechselt auch der Port/das Gerät für den Upload.




[env:esp32_receiver]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200

build_src_filter =
	-<*>
    +<main_receiver.cpp>
    +<receiver_ble.cpp>

upload_port = COM5 ; Change -> PIO Home -> left hand Devices -> Port
monitor_port = COM5 ; Durch die Angabe von Port könnte man mehrere Geräte angesteckt haben und mit wechsel der ENV wechselt auch der Port/das Gerät für den Upload.
